//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitOfWorkRepositoryExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMapping
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
    }
}
